### ISSUE TITLE
There is no assignment 2 yet

### ISSUE THREAD

**Issue by Hendrikto** [rubigdata/course#3]
Since the werkcollege is tomorrow already, I would like to take a look at the second assignment to prepare for the werkcollege, and to get a chance to work out what problems I will encounter, so I can ask good question tomorrow.

**Comment by arjenpdevries** [comment]
Assignment 2 was not ready yet - every year, all the background software changes, so I need to do quite some testing to ensure the instructions are valid and clear, and do not confuse students rather than enlighten them.
